## Random Forest Model Demo with Heart.CSV file

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt, seaborn as sns


In [5]:
import os
os.getcwd()

'F:\\Python Learning\\Imarticus\\Projects\\Random Forest'

In [30]:
## Importing the dataset
df = pd.read_csv('Heart.csv')
df.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No

In [31]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [32]:
df.head()

Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0   63    1       typical     145   233    1        2    150      0      2.3   
1   67    1  asymptomatic     160   286    0        2    108      1      1.5   
2   67    1  asymptomatic     120   229    0        2    129      1      2.6   
3   37    1    nonanginal     130   250    0        0    187      0      3.5   
4   41    0    nontypical     130   204    0        2    172      0      1.4   

   Slope   Ca        Thal  AHD  
0      3  0.0       fixed   No  
1      2  3.0      normal  Yes  
2      2  2.0  reversable  Yes  
3      3  0.0      normal   No  
4      1  0.0      normal   No

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Age        303 non-null    int64  
 1   Sex        303 non-null    int64  
 2   ChestPain  303 non-null    object 
 3   RestBP     303 non-null    int64  
 4   Chol       303 non-null    int64  
 5   Fbs        303 non-null    int64  
 6   RestECG    303 non-null    int64  
 7   MaxHR      303 non-null    int64  
 8   ExAng      303 non-null    int64  
 9   Oldpeak    303 non-null    float64
 10  Slope      303 non-null    int64  
 11  Ca         299 non-null    float64
 12  Thal       301 non-null    object 
 13  AHD        303 non-null    object 
dtypes: float64(2), int64(9), object(3)
memory usage: 33.3+ KB


In [17]:
df.describe()

Age         Sex      RestBP        Chol         Fbs     RestECG  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.438944    0.679868  131.689769  246.693069    0.148515    0.990099   
std      9.038662    0.467299   17.599748   51.776918    0.356198    0.994971   
min     29.000000    0.000000   94.000000  126.000000    0.000000    0.000000   
25%     48.000000    0.000000  120.000000  211.000000    0.000000    0.000000   
50%     56.000000    1.000000  130.000000  241.000000    0.000000    1.000000   
75%     61.000000    1.000000  140.000000  275.000000    0.000000    2.000000   
max     77.000000    1.000000  200.000000  564.000000    1.000000    2.000000   

            MaxHR       ExAng     Oldpeak       Slope          Ca  
count  303.000000  303.000000  303.000000  303.000000  299.000000  
mean   149.607261    0.326733    1.039604    1.600660    0.672241  
std     22.875003    0.469794    1.161075    0.616226    0.937438  
min     71.000000    0.000000    0.000000    1.000000    0.000000  
25%    133.500000    0.000000    0.000000    1.000000    0.000000  
50%    153.000000    0.000000    0.800000    2.000000    0.000000  
75%    166.000000    1.000000    1.600000    2.000000    1.000000  
max    202.000000    1.000000    6.200000    3.000000    3.000000

In [34]:
missvalues = df.isnull().sum()
missvalues[missvalues > 0]

Ca      4
Thal    2
dtype: int64

In [35]:
df[df.Ca.isnull()]

Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
166   52    1    nonanginal     138   223    0        0    169      0   
192   43    1  asymptomatic     132   247    1        2    143      1   
287   58    1    nontypical     125   220    0        0    144      0   
302   38    1    nonanginal     138   175    0        0    173      0   

     Oldpeak  Slope  Ca        Thal  AHD  
166      0.0      1 NaN      normal   No  
192      0.1      2 NaN  reversable  Yes  
287      0.4      2 NaN  reversable   No  
302      0.0      1 NaN      normal   No

In [37]:
df[df.Thal.isnull()]

Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
87    53    0    nonanginal     128   216    0        2    115      0   
266   52    1  asymptomatic     128   204    1        0    156      1   

     Oldpeak  Slope   Ca Thal  AHD  
87       0.0      1  0.0  NaN   No  
266      1.0      2  0.0  NaN  Yes

In [18]:
df.Ca.value_counts()

0.0    176
1.0     65
2.0     38
3.0     20
Name: Ca, dtype: int64

In [36]:
df.groupby(['ChestPain','Sex','Ca'])['Ca'].size()

ChestPain     Sex  Ca 
asymptomatic  0    0.0    25
                   1.0     2
                   2.0     9
                   3.0     4
              1    0.0    41
                   1.0    32
                   2.0    20
                   3.0    10
nonanginal    0    0.0    26
                   1.0     9
              1    0.0    31
                   1.0    11
                   2.0     2
                   3.0     5
nontypical    0    0.0    11
                   1.0     4
                   2.0     3
              1    0.0    26
                   1.0     4
                   3.0     1
typical       0    0.0     3
                   2.0     1
              1    0.0    13
                   1.0     3
                   2.0     3
Name: Ca, dtype: int64

In [38]:
df.Ca.fillna(0.0, inplace=True)

In [24]:
df.groupby(['ChestPain','Sex','Thal'])['Thal'].size()

ChestPain     Sex  Thal      
asymptomatic  0    fixed          1
                   normal        27
                   reversable    12
              1    fixed         11
                   normal        26
                   reversable    66
nonanginal    0    normal        31
                   reversable     3
              1    fixed          2
                   normal        30
                   reversable    19
nontypical    0    normal        18
              1    fixed          2
                   normal        21
                   reversable     9
typical       0    normal         4
              1    fixed          2
                   normal         9
                   reversable     8
Name: Thal, dtype: int64

In [39]:
df.loc[87,'Thal'] = 'Normal'
df.loc[266,'Thal'] = 'reversable'

In [40]:
## Checking the missing values after updating the missing values
missvalues = df.isnull().sum()
missvalues[missvalues > 0]

Series([], dtype: int64)

In [51]:
## Checking the target variable 
df.AHD.value_counts()

No     164
Yes    139
Name: AHD, dtype: int64

In [72]:
for col in df.select_dtypes(include='object').columns:
    print(col)
    print()
    print(df[col].value_counts())
    print()

AHD

No     164
Yes    139
Name: AHD, dtype: int64



In [80]:
df.target = pd.get_dummies(df.AHD, drop_first = True, columns='Target')

AttributeError: 'DataFrame' object has no attribute 'AHD'

In [77]:
type(df.target)

pandas.core.frame.DataFrame

In [75]:
df.target.value_counts()

Yes
0      164
1      139
dtype: int64

In [68]:
df.Thal.replace('Normal','normal', inplace=True)

In [70]:
df.Thal.replace({'normal':0, 'reversable':1,'fixed':2}, inplace=True)

In [71]:
df.ChestPain.replace({'asymptomatic':0, 'nonanginal':1,'nontypical':2,'typical':3}, inplace=True)

In [73]:
## We created a target variable.  So let us drop 'AHD' variable
df.drop('AHD', axis=1, inplace= True)

In [78]:
## Concating both independent and target variables
df = pd.concat([df, df.target], axis=1)

In [86]:
df.columns

Index(['Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs', 'RestECG', 'MaxHR',
       'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'Target'],
      dtype='object')

In [85]:
df.rename(columns = {'Yes':'Target'},inplace=True)

In [87]:
y = df.iloc[:,-1]
X = df.iloc[:, 0:-1]

In [88]:
X.shape, y.shape

((303, 13), (303,))

In [89]:
df.shape

(303, 14)

In [90]:
## loading model libraries
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [91]:
## Splitting the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 100)

In [92]:
## Initialize the classifier
rf = RandomForestClassifier(n_jobs=-1)

In [93]:
## Fitting the model
rf.fit(X_train, y_train)


RandomForestClassifier(n_jobs=-1)

In [96]:
tr_pred = rf.predict(X_train)
test_pred = rf.predict(X_test)

In [98]:
confusion_matrix(y_train, tr_pred)

array([[125,   0],
       [  0, 102]], dtype=int64)

In [97]:
print(classification_report(y_train, tr_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       125
           1       1.00      1.00      1.00       102

    accuracy                           1.00       227
   macro avg       1.00      1.00      1.00       227
weighted avg       1.00      1.00      1.00       227



In [99]:
print(classification_report(y_test, test_pred))

              precision    recall  f1-score   support

           0       0.80      0.95      0.87        39
           1       0.93      0.76      0.84        37

    accuracy                           0.86        76
   macro avg       0.87      0.85      0.85        76
weighted avg       0.87      0.86      0.85        76



In [103]:
confusion_matrix(y_test, test_pred)

array([[37,  2],
       [ 9, 28]], dtype=int64)

In [110]:
y_test.value_counts()

0    39
1    37
Name: Target, dtype: int64

In [100]:
df.head()

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0   63    1          3     145   233    1        2    150      0      2.3   
1   67    1          0     160   286    0        2    108      1      1.5   
2   67    1          0     120   229    0        2    129      1      2.6   
3   37    1          1     130   250    0        0    187      0      3.5   
4   41    0          2     130   204    0        2    172      0      1.4   

   Slope   Ca  Thal  Target  
0      3  0.0     2       0  
1      2  3.0     0       1  
2      2  2.0     1       1  
3      3  0.0     0       0  
4      1  0.0     0       0

In [101]:
df.ChestPain.describe()

count    303.000000
mean       0.841584
std        0.960126
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        3.000000
Name: ChestPain, dtype: float64

In [102]:
df.ChestPain.dtype

dtype('int64')

In [115]:
df_feature_imp = pd.DataFrame(zip(X.columns, rf.feature_importances_), columns = ['colname','Imp'])

In [118]:
df_feature_imp.sort_values(by='Imp', ascending=False)

colname       Imp
2   ChestPain  0.130999
7       MaxHR  0.124730
12       Thal  0.124103
11         Ca  0.113888
9     Oldpeak  0.095289
4        Chol  0.083074
0         Age  0.081217
3      RestBP  0.079014
8       ExAng  0.067303
10      Slope  0.040648
1         Sex  0.031568
6     RestECG  0.017406
5         Fbs  0.010760

In [151]:
impcols = df.columns[df_feature_imp[df_feature_imp.Imp >= 0.05].index]
impcols

Index(['Age', 'ChestPain', 'RestBP', 'Chol', 'MaxHR', 'ExAng', 'Oldpeak', 'Ca',
       'Thal'],
      dtype='object')

In [119]:
params = {
    'max_depth': [2,3,5,10,20],
    'min_samples_leaf': [5,10,20,50,100,200],
    'n_estimators': [10,25,30,50,100,200]
}

In [120]:
# Instantiate the grid search model
grid_search = GridSearchCV(estimator=rf,
                           param_grid=params,
                           cv = 4,
                           n_jobs=-1, verbose=1, scoring="accuracy")

In [152]:
grid_search.fit(X_train[impcols], y_train)

Fitting 4 folds for each of 180 candidates, totalling 720 fits


GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=-1), n_jobs=-1,
             param_grid={'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100, 200],
                         'n_estimators': [10, 25, 30, 50, 100, 200]},
             scoring='accuracy', verbose=1)

In [153]:
grid_search.best_score_

0.8327067669172933

In [154]:
grid_search.best_params_

{'max_depth': 5, 'min_samples_leaf': 20, 'n_estimators': 100}

In [159]:
rf1 = RandomForestClassifier(max_depth= 5, min_samples_leaf= 20, n_estimators= 100, n_jobs=-1, random_state = 100)

In [160]:
rf1.fit(X_train[impcols], y_train)

RandomForestClassifier(max_depth=5, min_samples_leaf=20, n_jobs=-1,
                       random_state=100)

In [161]:
r_pred = rf1.predict(X_train[impcols])
t_pred = rf1.predict(X_test[impcols])

In [162]:
print(classification_report(y_train, r_pred))

              precision    recall  f1-score   support

           0       0.82      0.92      0.87       125
           1       0.89      0.75      0.81       102

    accuracy                           0.85       227
   macro avg       0.85      0.84      0.84       227
weighted avg       0.85      0.85      0.84       227



In [163]:
print(classification_report(y_test, t_pred))

              precision    recall  f1-score   support

           0       0.84      0.92      0.88        39
           1       0.91      0.81      0.86        37

    accuracy                           0.87        76
   macro avg       0.87      0.87      0.87        76
weighted avg       0.87      0.87      0.87        76



In [164]:
confusion_matrix(y_test, t_pred)

array([[36,  3],
       [ 7, 30]], dtype=int64)